### ISSUE TITLE
Desktop Support

### ISSUE THREAD

**Issue by JagadishaIncture** [the-best-is-best/kgoogle-map#2]
Any plan for supporting other platforms like web and desktop.

please refer this for Desktop

https://github.com/skillAndroid/openStreetMapComposeMultiplatform/tree/master

**Comment by the-best-is-best** [comment]
Until now all packages will support Android and iOS only

**Comment by JagadishaIncture** [comment]
@the-best-is-best  any future plans?

**Comment by the-best-is-best** [comment]
What new features are required in Android and iOS for Impl app? Do you have any idea?

**Comment by JagadishaIncture** [comment]
I think you have covered everything.

**Comment by the-best-is-best** [comment]
I'm sorry that Google Maps Development Kit only officially supports Android, iOS and Web, so desktop is not supported by Google.

**Comment by JagadishaIncture** [comment]
if that is the case let support Web Platform
